# Generated by Django 5.1.2 on 2024-11-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('idViaje', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Viaje')),
                ('direccionPartida', models.CharField(max_length=200, verbose_name='Dirección de Partida')),
                ('latitudPartida', models.DecimalField(decimal_places=20, max_digits=20, verbose_name='Latitud de Partida')),
                ('longitudPartida', models.DecimalField(decimal_places=20, max_digits=20, verbose_name='Longitud de Partida')),
                ('direccionDestino', models.CharField(max_length=200, verbose_name='Dirección de Destino')),
                ('latitudDestino', models.DecimalField(decimal_places=20, max_digits=20, verbose_name='Latitud de Destino')),
                ('longitudDestino', models.DecimalField(decimal_places=20, max_digits=20, verbose_name='Longitud de Destino')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('horaSalida', models.CharField(max_length=5, verbose_name='Hora de Salida')),
                ('asientos', models.IntegerField(verbose_name='Número de Asientos')),
            ],
        ),
    ]
