# Generated by Django 5.1.2 on 2024-11-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_usuario', '0002_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='latitudDestino',
            field=models.FloatField(verbose_name='Latitud de Destino'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='latitudPartida',
            field=models.FloatField(verbose_name='Latitud de Partida'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='longitudDestino',
            field=models.FloatField(verbose_name='Longitud de Destino'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='longitudPartida',
            field=models.FloatField(verbose_name='Longitud de Partida'),
        ),
    ]
